### PR TITLE
chore: merge v0.2.0 into master

### PR DESCRIPTION
**Pull request by danielolsen**
### Purpose

Update `master`, after which we will add a `v0.2.0` tag.

### Proposed release notes

Following the arbitrarily-selected format of JuMP release notes (with some edits to PR titles for clarity):

**Closed Issues:**
- Refactor for compatibility with JuMP v0.21 (#55)
- Improve documentation of pyreisejl (#69)
- Add support for asymmetric DC lines (#87)
- Add functionality to select the solver to be used (#97)
- Refactor the Gurobi.jl requirement (#101)
- Allow solver settings to be passed via pyreisejl (#102)

**Merged pull requests (features):**
- feat: allow specification of number of threads to run with (#66) (@danielolsen)
- feat: select number of gurobi threads from python (#67) (@danielolsen)
- feat, refactor: added new entry point to run call.py without PowerSimData (#74) (@ahurli)
- refactor: remove dependency of extract_data on ScenarioList (#75) (@ahurli)
- feat: Add Dockerfile (#85) (@ahurli)
- feat: enable differential pmin/pmax for DC lines (#91) (@danielolsen)
- REST API to launch simulation (#95) (@jon-hagg)
- refactor: accept Suboptimal if load shed is enabled (#96) (@danielolsen)
- feat: add flexibility for solvers besides Gurobi (#99) (@danielolsen)
- feat: implement more storage features (#103) (@danielolsen)
- refactor: remove Gurobi requirement (#106) (@danielolsen)

**Merged pull requests (fixes etc.):**
- Refactor for JuMP v0.21 compatibility (#62) (@danielolsen)
- Refactor for DataFrames v0.21 compatibility (#63) (@danielolsen)
- chore: change const paths to reflect new server file structure (#65) (@danielolsen)
- Add github action to check formatting (#68) (@jon-hagg)
- fix: correct path to data root dir (mnt) (#70) (@danielolsen)
- fix: refactor storage constraints for JuMP v0.21 compatibility (#71) (@danielolsen)
- fix: remove Julia exit which kills python (#72) (@danielolsen)
- fix: refactor load_shed var for JuMP v0.21 (#73) (@danielolsen)
- docs: add main title (#76) (@rouille)
- Add missing imports and run isort (#77) (@jon-hagg)
- Clean up bugs from call refactor (#78) (@danielolsen)
- ci: add flake8 and fix warnings (#79) (@jon-hagg)
- refactor: clean up thread specification in call.py (#82) (@ahurli)
- bug: update keep matlab flag to work as documentation indicates (#83) (@ahurli)
- Use pandas to update files (#84) (@rouille)
- Update Gurobi.jl to v0.9.3 (#86) (@danielolsen)
- Doc: Add documentation for pyreisejl usage (#88) (@ahurli)
- Fix bug with single storage in extract (#89) (@danielolsen)
- Add license (#90) (@rouille)
- Add .dockerignore (#92) (@jon-hagg)
- refactor: move arg parser to separate file (#93) (@jon-hagg)
- Installation documentation (#94) (@ToddG)
- fix: remove zero-padding for storage gen table (#100) (@danielolsen)
- Non blocking reads from process output (#105) (@jon-hagg)
- ci: use black profile for isort (#107) (@jon-hagg)
- fix: add parentheses for proper boolean algebra (#108) (@danielolsen)
- doc: update README to cover use of alternate solvers (#110) (@danielolsen)

### Time to review
15 minutes? I guess it depends how long it takes for us to decide what our release notes should look like.

### CODE REVIEW

**Comment by kasparm** [comment]
I think the release note is a bit too long.

Maybe for now just list the key features/fixes that were added in this release.

What we will aim for in the future is having a link to the detailed release note on a separate page.

**Comment by danielolsen** [comment]
@kasparm ideally we will be doing this more than once per year, so future ones will be shorter. What do you think about separating the 'merged PRs' section into 'features' (anything the user will see) and 'fixes etc.' (bug fixes, CI stuff, documentation)?

**Comment by kasparm** [comment]
@danielolsen that is fine with me for now. As said for the future we would like these reports on github short and and have a more detailed report on a separate page.

**Comment by danielolsen** [comment]
@kasparm I edited the proposed note above.

**Comment by kasparm** [comment]
Looks good. Don't forget to change the version number in Project.toml

**Comment by danielolsen** [comment]
> Looks good. Don't forget to change the version number in Project.toml

Done

**Review by kasparm — APPROVED** [review]

**Pull request merged**
